# Generated by Django 4.1.2 on 2022-10-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Chittagong', 'Chittagong'), ('Rangpur', 'Rangpur'), ('Rajshahi', 'Rajshahi'), ('Dhaka', 'Dhaka'), ('Jashore', 'Jashore'), ('Dinajpur', 'Dinajpur'), ('Sylhet', 'Sylhet'), ('Pabna ', 'Pabna '), ('Bogra', 'Bogra'), ('Noakhali', 'Noakhali'), ('Faridpur', 'Faridpur'), ('Barisal', 'Barisal'), ('Comilla', 'Comilla'), ('Mymensingh', 'Mymensingh')], max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=100)),
                ('profile', models.ImageField(blank=True, upload_to='profileimg')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
